- name: Set up suspension of bluetooth during sleep
  become: true
  when: not ansible_check_mode
  block:
    - name: Copy scripts
      ansible.builtin.copy:
        src: "../data/bluetooth/{{item}}"
        dest: "/usr/local/bin/{{item}}"
        remote_src: false
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      loop:
        - "stop_bluetooth"
        - "start_bluetooth"
    - name: Copy systemd units
      ansible.builtin.copy:
        src: "../data/systemd/{{item}}"
        dest: "/lib/systemd/system/{{item}}"
        remote_src: false
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      loop:
        - "restart-bluetooth-after-sleep.service"
        - "suspend-bluetooth-when-sleeping.service"
    - name: Start the systemd services
      ansible.builtin.systemd_service:
        state: started
        name: "{{item}}"
        daemon_reload: true
        enabled: true
      loop:
        - "restart-bluetooth-after-sleep.service"
        - "suspend-bluetooth-when-sleeping.service"
