- name: Upgrade packages and clean up old packages
  become: true
  block:
    - name: Add Flathub remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Install the flatpak packages
      community.general.flatpak:
        name:
          - com.bitwarden.desktop
          - com.github.zocker_160.SyncThingy
          - fr.romainvigier.MetadataCleaner
          - info.portfolio_performance.PortfolioPerformance
          - io.github.peazip.PeaZip
          - io.missioncenter.MissionCenter
          - io.podman_desktop.PodmanDesktop
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
        state: latest
